### ISSUE TITLE
UI: Heatmap of Traffic Pattern Activity per month

### ISSUE THREAD

**Issue by MartinYTSo** [Ein04/Mobility_Bias_Viz#12]
Heatmap of the biz data as shown in the midterm presentation what do you think @Ein04 @nancywan1004 ??

EDIT: Reference from the cross-walk team - https://alinac20.shinyapps.io/SurreyCrosswalk/#BUS_USAGE_KNN

**Comment by gouruiyu** [comment]
For the controls of heatmap, how do you think about the section of 'biz overlay' in the current UI sketch? #22

**Comment by MartinYTSo** [comment]
I think we should move the controls on the bottom right to the sidebar listed on the left.
