### ISSUE TITLE
Checkboxes for layer toggle disappear after check on Mac OS

### ISSUE THREAD

**Issue by gouruiyu** [Ein04/Mobility_Bias_Viz#13]
![image](https://user-images.githubusercontent.com/17880059/125696137-e939da96-5f41-414b-bd8b-8bcedefa5344.png)
Max OS Big Sur

![image](https://user-images.githubusercontent.com/72810148/125695476-f91bc337-38bc-4647-91c6-9f27d138275e.png)
Windows 10

**Comment by nancywan1004** [comment]
Wasn't able to reproduce on my end. :((
