### ISSUE TITLE
UI: UI rework to separate user controls and data display

### ISSUE THREAD

**Issue by gouruiyu** [Ein04/Mobility_Bias_Viz#22]
![um map  Data Explorer](https://user-images.githubusercontent.com/17880059/125833830-f36d7d01-0961-4061-815d-6883b639f6af.png)

**Comment by nancywan1004** [comment]
Can we do a single selection of vehicle types at a time? I'm thinking that later on, if we want to show the data on a heatmap, it would make more sense to only display it for one single vehicle type.

**Comment by gouruiyu** [comment]
> Can we do a single selection of vehicle types at a time? I'm thinking that later on, if we want to show the data on a heatmap, it would make more sense to only display it for one single vehicle type.

Yeah I agree, let's keep it as radio button for vehicle type selection then!

**Comment by MartinYTSo** [comment]
We should add a time slider that links the trends in heatmap and to the plot on the right.

**Comment by MartinYTSo** [comment]
![image](https://user-images.githubusercontent.com/72810148/125846877-a7bf4996-b8a7-4660-b63c-bd33ede58be2.png)

What do you think of using this as a sidebar panel instead of switching to dashboardPage?  This is from the shinypanels library linked here: https://github.com/datasketch/shinypanels
