### ISSUE TITLE
Default display of data

### ISSUE THREAD

**Issue by gouruiyu** [Ein04/Mobility_Bias_Viz#23]
This is minor setup/design choice that would need change in data processing and UI. 
When user first opens the app, with no camera selected, what should they see? 

I can think of two choices at this moment:
1. A default camera and its data of our choice. (could vary based on different postal code area)
2. No camera selected, the line plot shows the aggregated count of all 341 cameras.

What do you guys think? @nancywan1004 @MartinYTSo

**Comment by MartinYTSo** [comment]
I think a default camera would be fine.

**Comment by nancywan1004** [comment]
I agree with Martin on choosing a default camera. But do we have one right now? Is there a selected camera by default already?
